[package]

name = "rust-url-capi"
version = "0.0.1"
authors = ["Valentin Gosu <valentin.gosu@gmail.com>"]

[profile.dev]
opt-level = 3
debug = true
rpath = true
lto = true

[lib]
name = "rust-url-capi"
crate-type = ["staticlib"]

[dependencies.url]
path = "../rust-url"
